name: CI

on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/cache@v2.1.6
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-modules-
      - name: Use Node.js
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 16
      - run: yarn
      - run: yarn run lint
  build:
    runs-on: self-hosted
    needs: [lint]
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Use Node.js
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 16
      - run: yarn --pure-lockfile
      - run: yarn run build
  lighthouse:
    runs-on: self-hosted
    needs: [deploy]
    steps:
      - uses: actions/checkout@v2
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v7
        with:
          urls: |
            https://${{ env.BRANCH_SLUG }}.s3-website.fr-par.scw.cloud
          serverBaseUrl: ${{ secrets.LHCI_SERVER_BASE_URL }}
          serverToken: ${{ secrets.LHCI_SERVER_TOKEN }}
