name: CI

on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/cache@v2.1.6
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-modules-
      - name: Use Node.js
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 16
      - run: yarn
      - run: yarn run lint
  build:
    runs-on: self-hosted
    needs: [lint]
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Use Node.js
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 16
      - run: yarn --pure-lockfile
      - run: yarn run build
        env:
          SENTRY_URL: ${{secrets.SENTRY_URL}}
          SENTRY_ORG: ${{secrets.SENTRY_ORG}}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_DSN:  ${{ secrets.SENTRY_DSN }}
          SENTRY_LOG_LEVEL: ${{ secrets.SENTRY_LOG_LEVEL }}
          SENTRY_DRY_RUN: ${{ secrets.SENTRY_DRY_RUN }}

