name: Deploy

on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']
  push:
    branches:
      - master

jobs:
  deploy:
    strategy:
      matrix:
        node: [ '16' ]
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ matrix.node }}
      - run: yarn --pure-lockfile
      - run: yarn run build
      - run: yarn run export

      - name: Export custom variables
        run: |
          SAFE_GITHUB_HEAD_REF_SLUG_URL=$(echo $GITHUB_HEAD_REF_SLUG_URL | rev | cut -c-37 | rev)
          ([[ $GITHUB_REF == 'refs/heads/master' ]] && echo "BRANCH_SLUG=master" || echo "BRANCH_SLUG=$SAFE_GITHUB_HEAD_REF_SLUG_URL") >> $GITHUB_ENV

      - name: Configure SCW Credentials
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: 'test'
          AWS_ACCESS_KEY_ID: ${{ secrets.SCW_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SCW_SECRET_KEY }}
          AWS_REGION: 'fr-par'
          AWS_S3_ENDPOINT: 's3.fr-par.scw.cloud'
          SOURCE_DIR: 'opt'
