name: Deploy

on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']
  push:
    branches:
      - master

jobs:
  deploy:
    strategy:
      matrix:
        node: [ '14', '16' ]
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Use Node.js
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ matrix.node }}
      - run: yarn run build
      - run: yarn run export

      - name: Configure SCW Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.SCW_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SCW_SECRET_KEY }}
          aws-region: s3.fr-par.scw.cloud

      - name: Deploy static site to S3 bucket
        run: aws s3 sync ./out/ s3://${{ env.BRANCH_SLUG }} --delete
